ERROR_PATTERNS = [
    r'\bERROR\b',
    r'\bFAIL\b',
    r'\bFAILED\b',
    r'\bEXCEPTION\b',
    r'\bCRITICAL\b',
    r'\bFATAL\b',
    r'\bPANIC\b',
    r'\bTIMEOUT\b',
    r'\bDENIED\b',
    r'\bREJECTED\b',
    r'\bABORT\b',
    r'\bSEGMENTATION FAULT\b',
    r'\bOUT OF MEMORY\b',
    r'\bSTACK TRACE\b',
    r'\bTRACEBACK\b',
    r'\bUNHANDLED\b',
    r'\bHTTP/\d\.\d"\s(5\d\d|4\d\d)',
    r'\s(5\d\d|4\d\d)\s',
    r'\[error\]',
    r'\[emerg\]',
    r'\[crit\]',
    r'\[alert\]',
]